### PR TITLE
project: refine apk cmdline build

### PR DESCRIPTION
**Pull request by zhouwg**

### CODE REVIEW

**Comment by xionxiao** [comment]
Encountered an error when setup from a brand new environment:
```shell
bash: sdkmanager: command not found
```

cmdline-tools should be unzip into `${ANDROID_HOME}/cmdline-tools/latest` and then set:

```shell 
PATH=${ANDROID_HOME}/cmdline-tools/latest/bin:${PATH}
```

**Comment by zhouwg** [comment]
> Encountered an error when setup from a brand new environment:
> 
> ```shell
> bash: sdkmanager: command not found
> ```
> 
> cmdline-tools should be unzip into `${ANDROID_HOME}/cmdline-tools/latest` and then set:
> 
> ```shell
> PATH=${ANDROID_HOME}/cmdline-tools/latest/bin:${PATH}
> ```

thanks for your comment, I'll update it accordingly

**Review by xionxiao — APPROVED** [review]
Tested OK!

**Comment by zhouwg** [comment]
> Tested OK!

thanks for your time and feedback.

**Pull request merged**
